// src/pages-vue/user/UserList.vue
<template>
  <div>
    <h3 class="fw-600 margin-bottom-16">Manage user data</h3>
    <div class="text-grayest margin-bottom-24">All the data here are stored on mockapi.io, so shout out to them for providing such a cool service!</div>
    <template v-if="!loading">
      <div class="relative bg-white rounded-8 shadow-1 padding-24 margin-bottom-16">
        <div class="flex flex-justify-start flex-items-center">
          <div class="margin-right-16">
            <input type="text"
              class="form-text border-none bg-lightest padding-x-12 padding-y-4 fw-normal"
              placeholder="search name here.."
              v-model="search.name" />
          </div>
          <div class="margin-right-16">
            <input type="text"
              class="form-text border-none bg-lightest padding-x-12 padding-y-4 fw-normal"
              placeholder="search email here.."
              v-model="search.email" />
          </div>
        </div>
        <table class="table table-compact margin-y-20">
          <thead>
            <tr>
              <th class="th-shrink text-left">
                <div class="cursor-pointer flex flex-items-center">
                  <span class="margin-right-8"
                      @click="toggleSort('id')">
                    #
                  </span>
                  <span class="circle bg-lightest active-bg-light height-32px flex flex-items-center flex-justify-center margin-right-8" style="min-width: 32px;" 
                      @click="toggleSort('id')">
                    <i class="fa"
                      :class="[
                        sort.column === 'id' ? 'text-darkest' : 'text-gray',
                        sort.column === 'id' ?
                          (sort.order === 'ascending' ? 'fa-sort-down' : 'fa-sort-up') :
                          'fa-sort',
                      ]"></i>
                  </span>
                </div>
              </th>
              <th class="th-expand text-left">
                <div class="cursor-pointer flex flex-items-center">
                  <span class="margin-right-8"
                      @click="toggleSort('name')">
                    Name
                  </span>
                  <span class="circle bg-lightest active-bg-light height-32px flex flex-items-center flex-justify-center margin-right-8" style="min-width: 32px;" 
                      @click="toggleSort('name')">
                    <i class="fa fa-sort"
                      :class="[
                        sort.column === 'name' ? 'text-darkest' : 'text-gray',
                        sort.column === 'name' ?
                          (sort.order === 'ascending' ? 'fa-sort-down' : 'fa-sort-up') :
                          'fa-sort',
                      ]"></i>
                  </span>
                </div>
              </th>
              <th class="th-expand text-left">
                <div class="cursor-pointer flex flex-items-center">
                  <span class="margin-right-8"
                      @click="toggleSort('email')">
                    Email
                  </span>
                  <span class="circle bg-lightest active-bg-light height-32px flex flex-items-center flex-justify-center margin-right-8" style="min-width: 32px;" 
                      @click="toggleSort('email')">
                    <i class="fa"
                      :class="[
                        sort.column === 'email' ? 'text-darkest' : 'text-gray',
                        sort.column === 'email' ?
                          (sort.order === 'ascending' ? 'fa-sort-down' : 'fa-sort-up') :
                          'fa-sort',
                      ]"></i>
                  </span>
                </div>
              </th>
              <th class="th-shrink text-left">
                <div class="cursor-pointer flex flex-items-center">
                  <span class="margin-right-8"
                      @click="toggleSort('createdAt')">
                    Created at
                  </span>
                  <span class="circle bg-lightest active-bg-light height-32px flex flex-items-center flex-justify-center margin-right-8" style="min-width: 32px;" 
                      @click="toggleSort('createdAt')">
                    <i class="fa"
                      :class="[
                        sort.column === 'createdAt' ? 'text-darkest' : 'text-gray',
                        sort.column === 'createdAt' ?
                          (sort.order === 'ascending' ? 'fa-sort-down' : 'fa-sort-up') :
                          'fa-sort',
                      ]"></i>
                  </span>
                </div>
              </th>
              <th class="th-shrink text-left" colspan="2">
                Action
              </th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="(row, index) in queryData" :key="index">
              <td>{{ row.id }}</td>
              <td>{{ row.name }}</td>
              <td>{{ row.email }}</td>
              <td>{{ new Date(row.createdAt).toLocaleDateString() }}</td>
              <td>
                <router-link class="a hover-text-light text-nowrap fw-400" :to="$url(`/user/update/${row.id}`)">Update <i class="fa fa-angle-right margin-left-4 fw-400"></i></router-link>
              </td>
              <td>
                <span class="bg-lightest hover-bg-light active-bg-gray padding-x-12 padding-y-4 fw-normal rounded-4 cursor-pointer">...</span>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="margin-bottom-20 margin-bottom-24-sm flex flex-justify-between flex-justify-center-sm flex-items-center">
        <div class="margin-right-16">
          <select v-model="table.totalDataPerPage"
              class="form-dropdown border-none bg-white padding-x- padding-y-4 fw-normal cursor-pointer">
            <option :value="5">5 rows</option>
            <option :value="10">10 rows</option>
            <option :value="25">25 rows</option>
          </select>
        </div>
        <div class="margin-right-auto fw-500 text-gray">
          {{ (table.currentPage - 1) * table.totalDataPerPage + 1 }} -
          <template v-if="table.currentPage >= totalPage">
            {{ filteredData.length }}
          </template>
          <template v-else>
            {{ (table.currentPage - 1) * table.totalDataPerPage + table.totalDataPerPage }}
          </template>
          of
          {{ filteredData.length }}
        </div>
        <div class="margin-left-8">
          <button class="button border-none bg-white hover-bg-light active-bg-gray padding-x-12 padding-y-4 fw-normal"
              :disabled="table.currentPage <= 1"
              @click="table.currentPage--">
            Prev
          </button>
          <template v-for="(row, index) in pageButtons">
            <button :key="`pageButtons-${index}`"
                class="button margin-x-4 border-none padding-y-4 fw-normal"
                :class="
                  row && row === table.currentPage ?
                    'bg-black text-white padding-x-12' :
                    (row > 0 ? 'bg-white hover-bg-light active-bg-gray padding-x-12' : 'padding-x-4')
                "
                :disabled="row < 0"
                @click="table.currentPage = row">
              {{ row > 0 ? row : "..." }}
            </button>
          </template>
          <button class="button border-none bg-white hover-bg-light active-bg-gray padding-x-12 padding-y-4 fw-normal"
              :disabled="table.currentPage >= totalPage"
              @click="table.currentPage++">
            Next
          </button>
        </div>
      </div>
    </template>
    <div v-else>
      <div class="bg-white rounded-8 shadow-1 padding-24 margin-bottom-16">
        <table class="table table-compact">
          <thead>
            <tr role="row">
              <th class="th-shrink"><span class="skeleton rounded-4 height-24px width-32px"></span></th>
              <th class="th-expand"><span class="skeleton rounded-4 height-24px width-96px"></span></th>
              <th class="th-shrink"><span class="skeleton rounded-4 height-24px width-96px"></span></th>
              <th class="th-shrink"><span class="skeleton rounded-4 height-24px width-96px"></span></th>
              <th class="th-shrink"><span class="skeleton rounded-4 height-24px width-96px"></span></th>
              <th class="th-shrink"><span class="skeleton rounded-4 height-24px width-96px"></span></th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="i in [0, 1, 2, 3]" :key="i">
              <td class="th-shrink"><span class="skeleton rounded-4 height-24px width-24px"></span></td>
              <td class="th-expand"><span class="skeleton rounded-4 height-24px" :style="{width: `${Math.floor(Math.random() * (400 - 140 + 1) + 140)}px`}"></span></td>
              <td class="th-shrink"><span class="skeleton rounded-4 height-24px width-60px"></span></td>
              <td class="th-shrink"><span class="skeleton rounded-4 height-24px width-60px"></span></td>
              <td class="th-shrink"><span class="skeleton rounded-4 height-24px width-60px"></span></td>
              <td class="th-shrink"><span class="skeleton rounded-4 height-24px width-60px"></span></td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="margin-bottom-20 margin-bottom-24-sm flex flex-justify-between flex-justify-center-sm flex-items-center">
        <div>
          <div class="skeleton rounded-4 width-96px height-24px"></div>
        </div>
        <div class="hidden-sm flex flex-items-center">
          <div class="skeleton rounded-4 margin-left-12 height-24px width-28px"></div>
          <div class="skeleton rounded-4 margin-left-12 height-36px width-32px"></div>
          <div class="skeleton rounded-4 margin-left-12 height-24px width-76px"></div>
        </div>
      </div>
      <div class="hidden-sm-greater flex flex-justify-between">
        <div class="skeleton rounded-4 height-40px fill margin-right-8"></div>
        <div class="skeleton rounded-4 height-40px fill margin-left-8"></div>
      </div>
    </div>
  </div>
</template>

<script>
import api from '@/utils/api';
import queryData from '@/utils/queryData'

export default {
  name: 'UserList',
  data: function () {
    return {
      error: {
        object: null,
        title: '',
        message: '',
        showLoading: false,
      },
      loading: true,
      table: {
        data: null,
        totalDataPerPage: 5,
        currentPage: 1,
      },
      search: {
        name: '',
        email: '',
      },
      sort: {
        column: null,
        order: 'none', // 'ascending', 'descending'
      },
    };
  },
  async mounted () {
    this.fetchData();
  },
  computed: {
    filteredData: function () {
      return this.table.data &&
        queryData(this.table.data, {
          filterFunctions: (() => {
            let functions = [];
            if (this.search.name) {
              functions.push(row => row.name.match(this.search.name))
            }
            if (this.search.email) {
              functions.push(row => row.email.match(this.search.email))
            }
            return functions;
          })(),
        });
    },
    queryData: function () {
      return this.table.data &&
        queryData(this.table.data, {
          filterFunctions: (() => {
            let functions = [];
            if (this.search.name) {
              functions.push(row => row.name.match(this.search.name))
            }
            if (this.search.email) {
              functions.push(row => row.email.match(this.search.email))
            }
            return functions;
          })(),
          sortFunctions: (() => {
            let functions = [];
            if (this.sort.column) {
              functions.push((row1, row2) =>
                row1[this.sort.column] > row2[this.sort.column] &&
                this.sort.order === 'ascending' ?
                  1 : -1)
            }
            return functions;
          })(),
          totalDataPerPage: this.table.totalDataPerPage,
          currentPage: this.table.currentPage,
        });
    },
    pageButtons: function () {
      let first = 1,
          second = this.totalPage >= 2 ? 2 : null,
          third = this.totalPage >= 3 ? 3 : null,
          fourth = this.totalPage >= 4 ? 4 : null,
          fifth = this.totalPage >= 5 ? 5 : null;
      if (this.totalPage > 5) {
        if (this.table.currentPage <= 3) {
          fourth = -1;
          fifth = this.totalPage;
        } else if (this.table.currentPage > this.totalPage - 3) {
          second = -1;
          third = this.totalPage - 2;
          fourth = this.totalPage - 1;
          fifth = this.totalPage;
        } else {
          second = -1;
          third = this.table.currentPage;
          fourth = -1;
          fifth = this.totalPage;
        }
      }
      return [
        first,
        second,
        third,
        fourth,
        fifth,
      ].filter(Boolean);
    },
    totalPage: function () {
      console.log(this.filteredData)
      return this.filteredData ?
        Math.ceil(this.filteredData.length / this.table.totalDataPerPage) :
        0;
    },
  },
  methods: {
    fetchData () {
      this.loading = true;

      const handleError = (error) => {
        this.error = error;
        this.loading = false;
      }

      api.retry({ beforeRetry: handleError })
        .get("users")
        .then(function (response) {
          // this.table.data = response.data.filter((data, index) => index < 23);
          // this.table.data = [...this.table.data, ...this.table.data];
          this.table.data = response.data;
          this.error = null;
          this.loading = false;
        }.bind(this))
        .catch(this.handleError);
    },
    toggleSort (column) {
      let order = 'ascending';
      if (this.sort.column === column) {
        if (this.sort.order === 'none') {
          order = 'ascending';
        } else if (this.sort.order === 'ascending') {
          order = 'descending';
        } else {
          column = null;
          order = 'none';
        }
      }
      this.sort.column = column;
      this.sort.order = order;
    },
  },
}
</script>

// src/pages-react/user/UserList.jsx
import React from 'react';
import { useNavigate } from 'react-router-dom';

import api from '@/utils/api'
import handleError from '@/utils/handleError'
import i18next from '@/utils/i18next';
import queryData from '@/utils/queryData'
import url from '@/utils/url'

export default function UserList() {
  let t = i18next.t;
  let navigate = useNavigate();

  const isMounted = React.useRef(false);

  // data
  const [data, setData] = React.useState({
    error: {
      object: null,
      title: '',
      message: '',
      showLoading: false,
    },
    loading: false,
    table: {
      data: null,
      totalDataPerPage: 5,
      currentPage: 1,
    },
    search: {
      name: '',
      email: '',
    },
    sort: {
      column: null,
      order: 'none', // 'ascending', 'descending'
    },
  });

  // mounted
  React.useEffect(() => {
    isMounted.current = true;

    fetchData();
  }, []);

  // computed
  function totalPage () {
    return data.table.data ?
      Math.ceil(data.table.data.length / data.table.totalDataPerPage)
      : 0;
  }

  // methods
  function toggleSort (column) {
    let order = 'ascending';
    if (data.sort.column === column) {
      if (data.sort.order === 'none') {
        order = 'ascending';
      } else if (data.sort.order === 'ascending') {
        order = 'descending';
      } else {
        column = null;
        order = 'none';
      }
    }
    setData((prevData) => (
      prevData.sort.column = column,
      prevData.sort.order = order,
      { ...prevData }
    ))
  }

  function fetchData () {
    setData((prevData) => (
      prevData.loading = true,
      { ...prevData }
    ))

    const catchError = function (error) {
      if (error) {
        const [title, message, showLoading] = handleError(error);
        setData((prevData) => (
          prevData.error.object = error,
          prevData.error.title = title,
          prevData.error.message = message,
          prevData.error.showLoading = showLoading,
          { ...prevData }
        ))
      }
      setData((prevData) => (
        prevData.loading = false,
        { ...prevData }
      ))
    }

    api.retry({ beforeRetry: handleError })
      .get("users")
      .then(function (response) {
        setData((prevData) => (
          prevData.table.data = response.data.map((user, index) => (user.index = index, user)),
          prevData.error = null,
          prevData.loading = false,
          { ...prevData }
        ))
      })
      .catch(catchError);
  };

  return (
    <div>
      <div>
        active lang: {i18next.language}
      </div>
      <div>
        usage example: {t('components.errors.networkError.title')}
      </div>
      <div>
        available langs:
        {
          i18next.options.supportedLngs.slice(0, -1).map((lang, index) => (
            <span className="margin-left-4 cursor-pointer" key={index}
                onClick={e => {
                  navigate(url(null, lang));
                  // how the fuck i18next doesn't change the active lang
                  // when we've told its setting to read from first url path
                  // that's why we need this line
                  i18next.changeLanguage(lang);
                }}>
              {lang} ({url(null, lang)})
            </span>
          ))
        }
      </div>
      <table className="table table-compact">
        <thead>
          <tr>
            <th className="th-shrink text-left">
              <div className="cursor-pointer flex flex-items-center">
                <span className="margin-right-8"
                    onClick={e => setData((prevData) => (toggleSort('id'), { ...prevData }))}>
                  #
                </span>
                <span className="circle bg-lightest active-bg-light width-32px height-32px flex flex-items-center flex-justify-center margin-right-8"
                    onClick={e => setData((prevData) => (toggleSort('id'), { ...prevData }))}>
                  <i className={`fa
                    ${data.sort.column === 'id' ? 'text-darkest' : 'text-gray'}
                    ${
                      data.sort.column === 'id' ?
                        data.sort.order === 'ascending' ? 'fa-sort-down' : 'fa-sort-up' :
                        'fa-sort'
                    }
                  `}></i>
                </span>
              </div>
            </th>
            <th className="th-expand text-left">
              <div className="cursor-pointer flex flex-items-center">
                <span className="margin-right-8"
                    onClick={e => setData((prevData) => (toggleSort('name'), { ...prevData }))}>
                  Name
                </span>
                <span className="circle bg-lightest active-bg-light width-32px height-32px flex flex-items-center flex-justify-center margin-right-8"
                    onClick={e => setData((prevData) => (toggleSort('name'), { ...prevData }))}>
                  <i className={`fa
                    ${data.sort.column === 'name' ? 'text-darkest' : 'text-gray'}
                    ${
                      data.sort.column === 'name' ?
                        data.sort.order === 'ascending' ? 'fa-sort-down' : 'fa-sort-up' :
                        'fa-sort'
                    }
                  `}></i>
                </span>
                <input type="text"
                  className="form-text border-none padding-y-4 bg-lightest width-auto"
                  placeholder="search name here.."
                  onChange={e => {
                    const newValue = e.target.value;
                    setData((prevData) => (prevData.search.name = newValue, { ...prevData }))
                  }} />
              </div>
            </th>
            <th className="th-expand text-left">
              <div className="cursor-pointer flex flex-items-center">
                <span className="margin-right-8"
                    onClick={e => setData((prevData) => (toggleSort('email'), { ...prevData }))}>
                  Email
                </span>
                <span className="circle bg-lightest active-bg-light width-32px height-32px flex flex-items-center flex-justify-center margin-right-8"
                    onClick={e => setData((prevData) => (toggleSort('email'), { ...prevData }))}>
                  <i className={`fa
                    ${data.sort.column === 'email' ? 'text-darkest' : 'text-gray'}
                    ${
                      data.sort.column === 'email' ?
                        data.sort.order === 'ascending' ? 'fa-sort-down' : 'fa-sort-up' :
                        'fa-sort'
                    }
                  `}></i>
                </span>
                <input type="text"
                  className="form-text border-none padding-y-4 bg-lightest width-auto"
                  placeholder="search email here.."
                  onChange={e => {
                    const newValue = e.target.value;
                    setData((prevData) => (prevData.search.email = newValue, { ...prevData }))
                  }} />
              </div>
            </th>
            <th className="th-shrink text-left">
              <div className="cursor-pointer flex flex-items-center">
                <span className="margin-right-8"
                    onClick={e => setData((prevData) => (toggleSort('createdAt'), { ...prevData }))}>
                  Created at
                </span>
                <span className="circle bg-lightest active-bg-light width-32px height-32px flex flex-items-center flex-justify-center margin-right-8"
                    onClick={e => setData((prevData) => (toggleSort('createdAt'), { ...prevData }))}>
                  <i className={`fa
                    ${data.sort.column === 'createdAt' ? 'text-darkest' : 'text-gray'}
                    ${
                      data.sort.column === 'createdAt' ?
                        data.sort.order === 'ascending' ? 'fa-sort-down' : 'fa-sort-up' :
                        'fa-sort'
                    }
                  `}></i>
                </span>
              </div>
            </th>
          </tr>
        </thead>
        <tbody>
          {
            data.table.data &&
            queryData(data.table.data, {
              filterFunctions: (() => {
                let functions = [];
                if (data.search.name) {
                  functions.push(row => row.name.match(data.search.name))
                }
                if (data.search.email) {
                  functions.push(row => row.email.match(data.search.email))
                }
                return functions;
              })(),
              sortFunctions: (() => {
                let functions = [];
                if (data.sort.column) {
                  functions.push((row1, row2) =>
                    row1[data.sort.column] > row2[data.sort.column] &&
                    data.sort.order === 'ascending' ?
                      1 : -1)
                }
                return functions;
              })(),
              totalDataPerPage: data.table.totalDataPerPage,
              currentPage: data.table.currentPage,
            }).map((row, index) => (
              <tr key={index}>
                <td>{row.id}</td>
                <td>{row.name}</td>
                <td>{row.email}</td>
                <td>{new Date(row.createdAt).toLocaleDateString()}</td>
              </tr>
            ))
          }
        </tbody>
      </table>
      <div className="flex flex-justify-end">
        <div className="relative margin-right-12">
          <div className="padding-x-12 padding-x-16 padding-y-4 bg-lightest rounded-4">5 rows</div>
          {/*<div className="dropdown dropdown-bottom border border-dark">
            Hello World!
          </div>*/}
        </div>
        <div className="margin-right-12">
          <select className="form-dropdown border-none padding-y-4 bg-lightest width-auto">
            <option>5 rows</option>
            <option>10 rows</option>
            <option>25 rows</option>
          </select>
        </div>
        <div>
          <button className="button margin-x-4 border-none bg-lightest padding-x-12 padding-y-4 fw-normal"
              disabled={data.table.currentPage <= 1}
              onClick={e => setData((prevData) => (prevData.table.currentPage--, { ...prevData }))}>
            Prev
          </button>
          {
            ((totalData, totalDataPerPage, currentPage) => {
              let second, third, fourth;
              if (currentPage <= 3) {
                second = 2;
                third = 3;
                fourth = null;
              } else if (currentPage > totalPage() - 3) {
                second = null;
                third = totalPage() - 2;
                fourth = totalPage() - 1;
              } else {
                second = null;
                third = currentPage;
                fourth = null;
              }
              return [1, second, third, fourth, totalPage()];
            })(data.table.data && data.table.data.length, data.table.totalDataPerPage, data.table.currentPage).map((row, index) => (
              <button key={index}
                  className={`button margin-x-4 border-none padding-y-4 fw-normal
                      ${row && row === data.table.currentPage ?
                        'bg-black text-white padding-x-12' :
                        row ? 'bg-lightest padding-x-12' : 'padding-x-4'
                      }
                    `}
                  disabled={!row}
                  onClick={e => setData((prevData) => (prevData.table.currentPage = row, { ...prevData }))}>
                { row ? row : '...'}
              </button>
            ))
          }
          <button className="button margin-x-4 border-none bg-lightest padding-x-12 padding-y-4 fw-normal"
              disabled={data.table.currentPage >= totalPage()}
              onClick={e => setData((prevData) => (prevData.table.currentPage++, { ...prevData }))}>
            Next
          </button>
        </div>
      </div>
    </div>
  );
}
